# Generated by Django 4.0.2 on 2022-02-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('tazkira', models.CharField(max_length=50, unique=True)),
                ('hire_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('photo', models.ImageField(default='user.jpg', upload_to='employee/images')),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('full time', 'full time'), ('half time', 'half time'), ('absent', 'absent'), ('overtime', 'overtime')], default='full time', max_length=20)),
                ('overtime_amount', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('salary_per_hour', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
