# Generated by Django 4.0.2 on 2022-02-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_cash', models.CharField(max_length=100, unique=True)),
                ('amount_of_money', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('recived_date', models.DateField()),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='employees.employee')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sale')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_exp', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=20)),
                ('expence_for', models.CharField(choices=[('electricity', 'electricity'), ('rate', 'rate'), ('water', 'water'), ('food', 'food'), ('stationary', 'stationary'), ('packaging cost', 'packaging cost'), ('transport cost', 'transport cost'), ('maintenance cost', 'maintenance cost'), ('other', 'other')], max_length=20)),
                ('expence_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
