# Generated by Django 4.0.2 on 2022-02-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_farmer_alter_customer_address'),
        ('products', '0002_alter_buy_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.AddField(
            model_name='sale',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.farmer'),
            preserve_default=False,
        ),
    ]
