# Generated by Django 4.0.2 on 2022-02-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_buy_customer_remove_sale_farmer_buy_farmer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
