# Generated by Django 4.0.2 on 2022-02-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_buy_paid_amount_alter_buy_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='paid_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='buy',
            name='remined_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
