# Generated by Django 4.0.2 on 2022-02-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_buy_paid_amount_alter_buy_remined_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='product.jpg', upload_to='product/images'),
        ),
    ]
