# Generated by Django 4.0.2 on 2022-02-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
