# Generated by Django 4.0.2 on 2022-02-13 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_buy_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_of_sale',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 2, 13, 10, 56, 4, 546097, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
